export const projects = [
  {
    cardName: "iStore App",
    cardBackground: "/images/projects/istore-app/main.webp",
    cardDetails:
      "An e-commerce clothing store, utilizing Sylius platform's REST API and features for products. There is NO code or Demo for this project. I don't have the owner's permission to share it.",
    cardStack: "NextJS | TS | Redux | Axios | Shadcn UI | TailwindCSS",
    projectGit: "",
    projectDemo: "",
    projectImages: [
      "/images/projects/istore-app/main.webp",
      "/images/projects/istore-app/1.webp",
      "/images/projects/istore-app/2.webp",
      "/images/projects/istore-app/3.webp",
      "/images/projects/istore-app/4.webp",
      "/images/projects/istore-app/5.webp",
      "/images/projects/istore-app/6.webp",
      "/images/projects/istore-app/7.webp",
      "/images/projects/istore-app/8.webp",
      "/images/projects/istore-app/9.webp",
      "/images/projects/istore-app/10.webp",
      "/images/projects/istore-app/11.webp",
    ],
  },
  {
    cardName: "iBudget App",
    cardBackground: "/images/projects/budget-app/main.webp",
    cardDetails:
      "A personal spending management app, with the ability to track expenses and incomes, and generate Excel reports.",
    cardStack: "ReactJS | TS | Redux | React-Router | MUI | TailwindCSS",
    projectGit:
      "https://github.com/khaled-rashidi99/Budget-Spending-Management-App",
    projectDemo: "https://budget-spending-management-app.vercel.app/",
    projectImages: [
      "/images/projects/budget-app/main.webp",
      "/images/projects/budget-app/1.webp",
      "/images/projects/budget-app/2.webp",
      "/images/projects/budget-app/3.webp",
      "/images/projects/budget-app/4.webp",
      "/images/projects/budget-app/5.webp",
      "/images/projects/budget-app/6.webp",
    ],
  },
  {
    cardName: "iBook Library App",
    cardBackground: "/images/projects/book-library/main.webp",
    cardDetails:
      "A book library app, with the ability to borrow books integreted from APIs, view borrowing history, and return books after due date.",
    cardStack: "ReactJS | TS | React-Router | MUI | TailwindCSS",
    projectGit: "https://github.com/khaled-rashidi99/Book-Library",
    projectDemo: "https://ibook-library.vercel.app/",
    projectImages: [
      "/images/projects/book-library/main.webp",
      "/images/projects/book-library/1.webp",
      "/images/projects/book-library/2.webp",
      "/images/projects/book-library/3.webp",
      "/images/projects/book-library/4.webp",
      "/images/projects/book-library/5.webp",
      "/images/projects/book-library/6.webp",
      "/images/projects/book-library/7.webp",
      "/images/projects/book-library/8.webp",
      "/images/projects/book-library/9.webp",
    ],
  },
  {
    cardName: "iHMS App",
    cardBackground: "/images/projects/ihms-app/main.webp",
    cardDetails:
      "A hospital management system app, with the ability to add fake data for doctors, services, and other data. This is a functional template, the app needs integration with the hospital's APIs.",
    cardStack: "ReactJS | TS | Redux | Axios | React-Router | MUI",
    projectGit:
      "https://github.com/khaled-rashidi99/Hospital-Management-System",
    projectDemo: "https://ihospital-management-system.vercel.app/",
    projectImages: [
      "/images/projects/ihms-app/main.webp",
      "/images/projects/ihms-app/1.webp",
      "/images/projects/ihms-app/2.webp",
      "/images/projects/ihms-app/3.webp",
      "/images/projects/ihms-app/4.webp",
      "/images/projects/ihms-app/5.webp",
      "/images/projects/ihms-app/6.webp",
      "/images/projects/ihms-app/7.webp",
      "/images/projects/ihms-app/8.webp",
      "/images/projects/ihms-app/9.webp",
      "/images/projects/ihms-app/10.webp",
    ],
  },
];
